runtime: python313

instance_class: F1
automatic_scaling:
  max_instances: 1

handlers:
- url: /.*
  script: auto
env_variables:
  PUBSUB_VERIFICATION_TOKEN: '123token'
  PROJECT_ID: 'rlsac2024'
  TOPIC: 'cpu_temperature_alert'
  BOT_TOKEN: '5911142810:AAEQ1HUOoWrtnZQnGwp0qw95d7q_UT2rMLU'