runtime: python313

instance_class: F1
automatic_scaling:
  max_instances: 1

entrypoint: gunicorn main:app
service: web

handlers:
- url: /static
  static_dir: static
- url: /.*
  secure: always
  script: auto